# Generated by Django 2.1 on 2020-01-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200104_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('posted_by', models.CharField(max_length=200)),
                ('time_posted', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
